
POST http://localhost:3003/users
Content-Type: application/json

{
    "firstName": "Hamid" , 
    "lastName": "khavarie",
    "email": "hr.khavarieery9998ry1@gmail.com",
    "password": "Hrp@4545" 
}