
POST http://localhost:3003/users
Content-Type: application/json

{
    "firstName": "Hamid Reza" , 
    "lastName": "khavarie",
    "email":"hrp.develop@gmail.com" , 
    "password" : "Hrp@2545340"

}